### ISSUE TITLE
eqFTP won't connect

### ISSUE THREAD

**Issue by sasagit** [Equals182/eqFTP#114]
Every now and then eqFTP just won't connect, after I chose connection it just displays cog wheel.
If I delete connection and make new one it works.
I am using version 0.7.0.

**Comment by Equals182** [comment]
Please, follow theese steps to add debug information in your issue:
http://equals182.github.io/eqFTP/#creating-issue

**Comment by sasagit** [comment]
Hello, this is log
[node-log 10:59:48 AM] [eqFTP-ftpDomain]: Connecting to this ID: 1
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [c.c] There's no connection with this ID: 1. Or ftpDomain currently disconnecting from this server.
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 1. Queue cleared now.
3extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [c.d] There's no connection with this ID: 1. true

[node-log 10:59:48 AM] [eqFTP-ftpDomain]: Connecting to this ID: 1
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [c.c] There's no connection with this ID: 1. Or ftpDomain currently disconnecting from this server.
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 1. Queue cleared now.
3extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 10:59:48 AM] [eqFTP-ftpDomain]: [c.d] There's no connection with this ID: 1. true

**Comment by sasagit** [comment]
I noticed that this error can be reproduced by clicking on connect/disconnect button

**Comment by Equals182** [comment]
Can you please uninstall eqFTP and install it again from `https://github.com/Equals182/eqFTP` because I made some poor commits and it could be somehow involved here.
Right now version on this repository should work fine.

And please, confirm if I understood you right:
1. you create connection
2. Connect to it normally and it works fine
3. Then suddenly it stops working
4. Nothing helps unless you delete connection and create new one
Rght?

**Comment by sasagit** [comment]
I reinstalled from link above and after fast clicking on connect disconnect the problem is still there, it hangs with the following error log
[node-log 12:15:22 PM] [eqFTP-ftpDomain]: Connecting to this ID: 2
NodeDebugUtils.js:114 [node-error 12:15:22 PM] [eqFTP-ftpDomain]: [c.c] There's no connection with this ID: 2. Or ftpDomain currently disconnecting from this server.
NodeDebugUtils.js:114 [node-error 12:15:22 PM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 2. Queue cleared now.
NodeDebugUtils.js:114 [node-error 12:15:22 PM] [eqFTP-ftpDomain]: [c.d] There's no connection with this ID: 2. true

I found out that manual restart of breackets helps and it starts working again, reload F5 doesn't work.

**Comment by Equals182** [comment]
So, is fast clicking the only thing that cause this error or is it just a way to reproduce it?

**Comment by sasagit** [comment]
No just the way to reproduce it

**Comment by Equals182** [comment]
hm.. since it isn't the cause of error, I can't find a real cause yet. 
This error (`There's no connection with this ID: 2. Or ftpDomain currently disconnecting from this server.`) or this (`There's no connection with this ID: 2. true`) can be a signal that eqFTP is currently disconnecting from server. I've fixed console output already and I'll throw it in repository after about 2 hours so we could find a real cause.
I'll also add new `console.log` lines just for you to debug your particular issue. Please, stay tuned, I'll comment here when everything will be done.

**Comment by Equals182** [comment]
I've made some changes but they shouldn't touch your issue, though.
Please, update from this url `https://github.com/Equals182/Buggy-eqFTP`

Firstly, I tried to fix fast clicking issue, but it didn't worked out well. Node still hangs and you need either restart Brackets entirely or use Debug->Restart Node + F5.
Secondly, since fast clicking is just one of many ways to have an infinite cogwheel, please, give me a real problem. I mean, there's a situation, when your connections stop working. Try to wait for it to happen (don't do fast clicking of something) and then copy last chunk of log here. Then I'll try to analyse logs and give you a special version with log lines just for your situation so we could continue resolving this particular problem.

**Comment by sasagit** [comment]
Ok I couldn't reproduce the problem, but something else is wrong. I deleted one connection and added other, but new one is still using data from deleted connection?!
After restar I got this
![untitled-3](https://cloud.githubusercontent.com/assets/3532767/6670857/845563b4-cc01-11e4-85d0-be54140f9177.jpg)

and this is the log (I cleared personal data)

[node-error 5:14:37 PM] [eqFTP-ftpDomain]: [s.a] Can't authorize on connectionID: 0
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 5:14:37 PM] [eqFTP-ftpDomain]: true
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: Disconnecting...
/C:/Users/Sale/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1619 Object
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [TEST-ECONNRESET] Have client
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [TEST-ECONNRESET] Removing listeners
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [TEST-ECONNRESET] Listeners removed
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [TEST-ECONNRESET] Abort performed
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [TEST-ECONNRESET] Quit performed
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: Disonnected.
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 5:14:37 PM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 0. Queue cleared now.
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: Disconnecting...
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:37 PM] [eqFTP-ftpDomain]: Disonnected. Actually there was no client so nothing to disconnect.
/C:/Users/Sale/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1619 Object
/C:/Users/Sale/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1832 [eqFTP] Disconnected from server
/C:/Users/Sale/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1619 Object
/C:/Users/Sale/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1619 Object
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: Adding connections. Already here: [{"id":"0","order":"0","connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"off","sync":{"filecreation":false,"foldercreation":false,"fileupdate":false,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}},"ftpDomain":{"ignore":{},"processQueuePaused":false,"queue":{"a":[],"p":[],"f":[],"s":[]},"currentElement":{"type":"folder","connectionID":0,"path":"","id":"f_1426522472754491","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_STARTED","ftpDomain":{"diff":{"check":false,"action":false}}},"busy":true,"disconnecting":true},"listeners":{"error":null,"debug":null,"customError":null,"connect":null,"progress":null},"auth":false},{"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}},"id":1,"order":1,"ftpDomain":{"ignore":{}}},{"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":true,"ignore":""},"classic":{"uploadOnSave":true,"uploadOnSavePaused":false,"autoConnect":false}},"id":2,"order":2,"ftpDomain":{"ignore":{}}}] Adding: [{"id":"0","order":"0","connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"off","sync":{"filecreation":false,"foldercreation":false,"fileupdate":false,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}}},{"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}},"id":1,"order":1},{"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":true,"ignore":""},"classic":{"uploadOnSave":true,"uploadOnSavePaused":false,"autoConnect":false}},"id":2,"order":2}]
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 136: Checking connection ID: 0
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: {"id":"0","order":"0","connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"off","sync":{"filecreation":false,"foldercreation":false,"fileupdate":false,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}},"ftpDomain":{"ignore":{},"processQueuePaused":false,"queue":{"a":[],"p":[],"f":[],"s":[]},"currentElement":{"type":"folder","connectionID":0,"path":"","id":"f_1426522472754491","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_STARTED","ftpDomain":{"diff":{"check":false,"action":false}}},"busy":true,"disconnecting":true},"listeners":{"error":null,"debug":null,"customError":null,"connect":null,"progress":null},"auth":false}
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 136: Checking connection ID: 1
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: {"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":false,"ignore":""},"classic":{"uploadOnSave":false,"uploadOnSavePaused":false,"autoConnect":false}},"id":1,"order":1,"ftpDomain":{"ignore":{}}}
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 136: Checking connection ID: 2
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 147: Getting existent connection by ID, result: {"connectionName":"*********","server":"*********","port":"21","protocol":"ftp","username":"*********","password":"*********","localpath":"*********","remotepath":"*********","useList":false,"keepAlive":"10","timeOffset":"0","RSA":"","automatization":{"type":"sync","sync":{"filecreation":false,"foldercreation":false,"fileupdate":true,"rename":false,"delete":false,"checkdiff":true,"ignore":""},"classic":{"uploadOnSave":true,"uploadOnSavePaused":false,"autoConnect":false}},"id":2,"order":2,"ftpDomain":{"ignore":{}}}
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 5:14:44 PM] [eqFTP-ftpDomain]: 150: Checking if creditials are not same
NodeDebugUtils.js:117 [node-log 5:15:07 PM] [eqFTP-ftpDomain]: 1816: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":0,"path":"","id":"f_142652250790484","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
main.js:1619 Object {event: "queue_update", connectionID: 0, element: Object}
NodeDebugUtils.js:117 [node-log 5:15:07 PM] [eqFTP-ftpDomain]: [q.p] Queue is busy now.

**Comment by Equals182** [comment]
Please update from https://github.com/Equals182/Buggy-eqFTP Yes, again.
I'm sorry for that. I fixed some stuff and it should work fine.

**Comment by sasagit** [comment]
I still have undefined, do I have to delete some settings?

**Comment by Equals182** [comment]
Uhh.. This is confusing. It looks like you already using latest version...
Give me a couple of minutes, I'm gonna make some tests. Gonna add, delete, restart and stuff.

**Comment by Equals182** [comment]
So, I've deleted my connections and made a lot of tests. I wasn't able to reproduce your issue but I got a lot of others. I've fixed some stuff and you can update from https://github.com/Equals182/Buggy-eqFTP again. I could recommend you to close Brackets and (re)move `.remotesettings` file from **Folder for Settings** (this is path in main eqFTP settings). This will delete about 90% of eqFTP settings. Then you will be able to setup it again and it should work fine. Oh god I hope it will work fine.

**Comment by sasagit** [comment]
I am sorry but it is still the same. I uninstalled extension, deleted .remotesettings from Folder for Settings and from project folder (probably from some old version). I installed again from the link and it worked until brackets restart, again with "undefined" problem.

Here is log:
```
Attempting to register a command with a missing name, id, or command function:undefined eqftp.downloadFile
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.downloadFileAndOpen
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.addToPausedQueue-d
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.addToPausedQueue-u
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.addToAutomaticQueue-u
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.rename
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.delete
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.queueTaskStart
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.queueTaskPause
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.queueTaskRemove
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.queueTaskRestart
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.redownloadFile
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.createRemoteFile
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.createRemoteFolder
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.createRemoteFileRoot
/command/CommandManager.js:199 Attempting to register a command with a missing name, id, or command function:undefined eqftp.createRemoteFolderRoot
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.downloadFileAndOpen
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.downloadFile
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToPausedQueue-d
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.rename
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.delete
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFile
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFolder
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.downloadFile
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToPausedQueue-d
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.rename
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.delete
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFile
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFolder
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFileRoot
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.createRemoteFolderRoot
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.queueTaskStart
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.queueTaskPause
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.queueTaskRestart
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.queueTaskRemove
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToAutomaticQueue-u
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToPausedQueue-u
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.redownloadFile
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToAutomaticQueue-u
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.addToPausedQueue-u
/command/Menus.js:571 addMenuItem(): commandID not found: eqftp.redownloadFile
```

**Comment by Equals182** [comment]
Can you connect to your servers corretly? Does every server you connect uses right data? Can you add connections, remove them and correctly connect to them without restarting?

**Comment by sasagit** [comment]
Yes everything is working untill restart

**Comment by Equals182** [comment]
Does those log lines you posted in your last post shows up every time you start Brackets?

**Comment by sasagit** [comment]
Yes every time

**Comment by Equals182** [comment]
What language do you use in Brackets?

**Comment by sasagit** [comment]
default english

**Comment by sasagit** [comment]
ok now I deleted all settings from eqftp from preferences file brackets.json, but now I can't even install eqftp, this is the error that I get
thirdparty/requirejs/require.js:141 Uncaught Error: Mismatched anonymous define() module: function (require, exports, module)

After that i uninstalled Brackets completly, and important I deleted settings left in C:\Users\{username}\AppData\Roaming\Brackets\, than I reinstalled Brackets and eqFTP and for now everytnihg works fine.
It seems that after reinstaling different versions of eqFTP something went wrong and settings were written somewhere that couldn't be overwritten.

I'll test now to see if there will be any problems.

**Comment by Equals182** [comment]
Well, may be you're right. Settings are changing constantly with new version. I'm trying hard to make them compatible with older versions of eqFTP but looks like it didn't worked for you.
I'm really sorry for this inconvenience. I hope it will work fine since now and you will continue using this extension.
Thank you for your patience.

**Comment by sasagit** [comment]
Hello, sorry to say but there are still problems.
I get Can't get in directory error often.
Now again I get infinite cogwheel problem again.
The log is
[node-log 9:49:14 AM] [eqFTP-ftpDomain]: 1775: [q.a] Queue updated: {"a":[{"type":"folder","connectionID":1,"path":"/","id":"f_1426754879155226","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"/img/starka","id":"f_14267548791551","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"/css","id":"f_14267548791552","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"/js","id":"f_14267548791553","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"/img/babica","id":"f_14267548791554","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"","id":"f_142675492474924","state":"opened","queue":"a","status":"QUEUE_TASK_STATUS_WAITING"},{"type":"folder","connectionID":1,"path":"","id":"f_1426754954013902","state":"opened","queue":"a"}],"p":[],"f":[],"s":[]}
main.js:1560 Object {event: "queue_update", connectionID: 1, element: Object}
NodeDebugUtils.js:117 [node-log 9:49:14 AM] [eqFTP-ftpDomain]: [q.p] Queue is busy now.

**Comment by Equals182** [comment]
Can you please restart Brackets and send me full log after first error appearance?

**Comment by sasagit** [comment]
I didn't get the log after the first error apppearance, that was the log after F5 restart. After manual restart everything works again. I'll try to reproduce the problem and send the log

**Comment by sasagit** [comment]
But here is new error after deleting directory on server

Exception in 'eqFTP:events' listener on NodeConnection {domains: Object, _registeredModules: Array[1], _pendingInterfaceRefreshDeferreds: Array[0], _pendingCommandDeferreds: Array[371], _autoReconnect: true…}_autoReconnect: true_commandCount: 371_eventHandlers: Object_pendingCommandDeferreds: Array[371]_pendingInterfaceRefreshDeferreds: Array[0]_port: 58729_registeredModules: Array[1]_ws: WebSocketdomainEvents: Objectdomains: Object__proto__: NodeConnection TypeError: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
NodeConnection._receive
/utils/EventDispatcher.js:225 Assertion failed:/utils/EventDispatcher.js:225 trigger/utils/EventDispatcher.js:260 triggerWithArray/utils/NodeConnection.js:479 NodeConnection._receive
main.js:1560 Object {event: "working", work: false}

**Comment by Equals182** [comment]
This may be the cause. This probably crushed node and nothing will work after this (until you restart Node or restart Brackets manually)

**Comment by Equals182** [comment]
Can you provide a full log so I could get information about what been successfully done and what caused this error? I checked folder deletion events and there's almost nothing that can cause this error. This might be another event, but I don't know which one.

**Comment by sasagit** [comment]
Does this helps

[node-log 10:50:21 AM] [eqFTP-ftpDomain]: Connecting to this ID: 1
NodeDebugUtils.js:117 [node-log 10:50:21 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:117 [node-log 10:50:21 AM] [eqFTP-ftpDomain]: Connecting to this ID: 1
NodeDebugUtils.js:117 [node-log 10:50:21 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 1
NodeDebugUtils.js:114 [node-error 10:50:21 AM] [eqFTP-ftpDomain]: {"code":"EPIPE"}
NodeDebugUtils.js:114 [node-error 10:50:21 AM] [eqFTP-ftpDomain]: [q.p] Can't connect to server on connectionID: 1. Queue cleared now.
NodeDebugUtils.js:117 [node-log 10:50:21 AM] [eqFTP-ftpDomain]: Disconnecting...
NodeDebugUtils.js:117 [node-log 10:50:21 AM] [eqFTP-ftpDomain]: Disonnected. Actually there was no client so nothing to disconnect.
NodeDebugUtils.js:117 [node-log 10:50:21 AM] DEBUG:  user_command
NodeDebugUtils.js:117 [node-log 10:50:21 AM] "TYPE I"
main.js:1560 Object {event: "queue_update", connectionID: 1, element: Object}
main.js:1560 Object {event: "working", work: true}
main.js:1560 Object {event: "queue_update", connectionID: 1, element: Object}
main.js:1560 Object {event: "server_connection_error", err: Object, connectionID: 1}
main.js:1560 Object {event: "server_disconnect", connectionID: 1, clearQueue: true}
main.js:1773 [eqFTP] Disconnected from server

**Comment by Equals182** [comment]
Kind of. Still not enough information where *EPIPE* error appears. I've added some stuff that could help a bit more. Could you please update from this link: https://github.com/Equals182/Buggy-eqFTP and repeat your actions so we could get new logs?

**Comment by sasagit** [comment]
sorry for not answering so long
here is the error that I get now

 File watchers went offline!
NodeDebugUtils.js:114 [node-error 12:37:55 PM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'on' of undefined
    at Object.self.openPassive.callback (C:\Users\***\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:263:24)
    at Object.self.raw.callback (C:\Users\***\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:531:31)
    at Ftp.parseResponse (C:\Users\***\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:242:38)
    at Stream.<anonymous> (C:\Users\***\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:101:14)
    at Stream.EventEmitter.emit (events.js:95:17)
    at ResponseParser.reemit (C:\Users\***\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\node_modules\event-stream\node_modules\duplexer\index.js:70:25)
    at ResponseParser.EventEmitter.emit (events.js:95:17)
    at ResponseParser.<anonymous> (_stream_readable.js:746:14)
    at ResponseParser.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
NodeDebugUtils.js:114 [node-info 12:37:55 PM] [Server] stopping
8/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:58571/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:949 Watching disabled for C:/web/html/
/utils/EventDispatcher.js:224 Exception in 'documentSaved' listener on Object TypeError: Cannot read property 'addToQueue' of undefined TypeError: Cannot read property 'addToQueue' of undefined
    at Object.<anonymous> (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1573:49)
    at Function.n.extend.each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:2882)
    at Object.eqFTP.ftp.queue.add (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1567:19)
    at file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3203:49
    at String.<anonymous> (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1100:41)
    at Function.n.extend.each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:2882)
    at file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1094:27
    at Object.eqFTP.sf.settings.read (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1064:25)
    at Object.eqFTP.sf.connections.getByPath (file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1090:35)
    at file:///C:/Users/***/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3183:38
/utils/EventDispatcher.js:225 Assertion failed:
NodeDebugUtils.js:117 [node-log 12:38:06 PM] [eqFTP-ftpDomain] Loaded

**Comment by Equals182** [comment]
I forgot what was your problem. I'm gonna re-read this thread in the near future

**Comment by Equals182** [comment]
### Hello there!

I know this issue been there for a pretty long time, but I have some good news here!
We just released eqFTP v**1.0.0-beta.0** (v1-b for short I guess) and we're completely discontinuing support of all previous versions of this plugin.
New version works great on Brackets 1.8 and it should be good on lower versions too.

So yeah, we're closing and locking this issue forever and looking forward for you to try out our new version of eqFTP.
I'm sorry if I somehow disturbed you, or you lost your interest in eqFTP or Brackets in general, we're not going to make any noise here again.

If you have any questions, please contact me via email (you can find it in [my profile](https://github.com/Equals182)) or [Telegram app](http://t.me/equals182)

Thank you for understanding 😊
